from .register import *
from .login import *
from .index import *
from .category import *
from .product import *
from .cart import *
from .productInfo import *
from .ajax_views import *
from .profile import *
from .comments import *